num_epoch: 200
max_epoch: 120
patient: 20
log_iter: 1000

seed: 2021
cv_fold: 1
val_ratio: 0.125

# data
batch_size: 8
same_psize: 128
p_batch_size: 2048
img_transform: strong
img_size: 256
mul_scale_input: true
mul_scale_ratio: 4.

num_workers: 8
pin_memory: true
channels_last: true
image_input: true
lmdb: true
prefetch_factor: 3

# model
model: e2e_r18_abmilx
input_dim: 256
act: gelu
no_mil_bias: true
mil_norm: ln
# abmilx
n_heads: 4
abx_attn_plus: true
ffn: true

# train
mm: 0.9999
test_type: both_ema
amp: true
no_deter_algo: true
sdpa_type: torch
sync_bn: true
pad_enc_bs: true
all_patch_train: true